### ISSUE TITLE
void

### ISSUE THREAD

**Issue by lazaridiscom** [satran004/aion4j-maven-plugin#22]

**Comment by satran004** [comment]
It's little difficult to change now as the docs are all referring as aion4j. Also the umbrella project is aion4j. But I will try to see if we can have an additional short alias like  a4j or aion.

**Comment by lazaridiscom** [comment]
be aware that the major problem is the "4", as it forces a larger "travel" of the typing fingers.

(And the docs are early-draft at best, so changing them should not be that much of a problem.)
